### ISSUE TITLE
Empty Results 

### ISSUE THREAD

**Issue by siduck** [algolia/docsearch#1823] opened 2023-03-15 02:33 UTC
Hi there, I added docsearch to my site and it shows the auto-compeletion popup but i dont see any autocompletions or results at all
 
 
![image](https://user-images.githubusercontent.com/59060246/225190273-7c3d7368-7e1d-43fc-a02d-54722b439f8a.png)

 ```
 appId: "BOJS19CH35",
 apiKey: "c74ee96af1dea95b6e189501983733f8",
 indexName: "nvchad",
 ```

**Comment by shortcuts** [comment] 2023-03-15 07:24
Hey! Looking at your Crawler, we did not managed to get any records in. Can you try restarting it?

**Comment by siduck** [comment] 2023-03-15 07:39
ok restarted it 
![image](https://user-images.githubusercontent.com/59060246/225239253-73701aaf-73bc-4c63-be95-9cf1f3b7b0b0.png)

**Comment by siduck** [comment] 2023-03-15 07:39
Do I need a sitemap.xml? docsearch docs didnt mention anything about it

**Comment by shortcuts** [comment] 2023-03-15 07:43
> Do I need a sitemap.xml? docsearch docs didnt mention anything about it

Nope you don't, it's nice to have since it helps the Crawler finding new pages

-----

I took a look at your Crawler and it seems to be configured for a Docusaurus website, but isn't one. I fixed the config, it should work better now :)

**Comment by siduck** [comment] 2023-03-15 07:46
Thx! It does show the results now 
![image](https://user-images.githubusercontent.com/59060246/225241130-a7976af1-ba2d-4135-a87a-832f181ad3ba.png)

but there are very few ( and too of the home page ) 

clicking them points to a nonexistent id

![image](https://user-images.githubusercontent.com/59060246/225241421-91b1e346-9027-4da9-a759-5f1396e3aeb2.png)

**Comment by siduck** [comment] 2023-03-15 07:47
> Nope you don't, it's nice to have since it helps the Crawler finding new pages
 
 So without it the crawler wouldnt find new pages?

**Comment by shortcuts** [comment] 2023-03-15 07:49
> > Nope you don't, it's nice to have since it helps the Crawler finding new pages
> 
> So without it the crawler wouldnt find new pages?

It helps with consistency, especially with client-side rendered websites. Here it seems that it doesn't manage to discover every pages of your website, so it would really help

**Comment by shortcuts** [comment] 2023-03-15 07:52
> but there are very few ( only of the home page )

Does your website apply some redirects? For example, when we crawl this page `https://nvchad.com/#/docs/quickstart/install`, it redirects to `https://nvchad.com/#/`

**Comment by siduck** [comment] 2023-03-15 07:53
> > but there are very few ( only of the home page )
> 
> Does your website apply some redirects? For example, when we crawl this page `https://nvchad.com/#/docs/quickstart/install`, it redirects to `https://nvchad.com/#/`

No

**Comment by siduck** [comment] 2023-03-15 07:54
I got no idea why it redirects there, im using hashrouter ( in my solid-router settings ) , does that affect anything?

**Comment by siduck** [comment] 2023-03-15 07:57
asked chatgpt :exploding_head: 

![image](https://user-images.githubusercontent.com/59060246/225243739-e21a928c-e033-4c0a-bdf3-9369c66d5eaf.png)

**Comment by shortcuts** [comment] 2023-03-15 07:57
> I got no idea why it redirects there, im using hashrouter ( in my solid-router settings ) , does that affect anything?

I'd assume so, it seems that `https://nvchad.com/#/docs/quickstart/install` renders the home page, it's not a redirect actually my bad.

I can reproduce by going to [the editor](https://crawler.algolia.com/admin/crawlers/e120626d-7695-43f1-b9bf-b19726525e9b/configuration/edit) -> URL tester with `https://nvchad.com/#/docs/quickstart/install` -> and on the `HTML` section you'll see the homepage rendered

**Comment by shortcuts** [comment] 2023-03-15 07:58
> asked chatgpt :exploding_head: 

HUGE ahaha

**Comment by siduck** [comment] 2023-03-15 07:59
> > I got no idea why it redirects there, im using hashrouter ( in my solid-router settings ) , does that affect anything?
> 
> I'd assume so, it seems that `https://nvchad.com/#/docs/quickstart/install` renders the home page, it's not a redirect actually my bad.
> 
> I can reproduce by going to [the editor](https://crawler.algolia.com/admin/crawlers/e120626d-7695-43f1-b9bf-b19726525e9b/configuration/edit) -> URL tester with `https://nvchad.com/#/docs/quickstart/install` -> and on the `HTML` section you'll see the homepage rendered

oh what would be the solution to this then? I've to use hashrouter method in solid-router compulsory

**Comment by shortcuts** [comment] 2023-03-15 08:04
> oh what would be the solution to this then? I've to use hashrouter method in solid-router compulsory 

I've never implemented such routing sorry! I know we had user with similar cases, I guess the repo of the tools you use would have the answers

**Comment by siduck** [comment] 2023-03-15 08:11
> > oh what would be the solution to this then? I've to use hashrouter method in solid-router compulsory
> 
> I've never implemented such routing sorry! I know we had user with similar cases, I guess the repo of the tools you use would have the answers

https://github.com/algolia/docsearch/pull/648

**Comment by shortcuts** [comment] 2023-03-15 08:24
Ah yes for the links, indeed! For the discovering of the pages, I'd say a sitemap would solve all problems

**Comment by siduck** [comment] 2023-03-15 08:35
> Ah yes for the rendered links, indeed! For the discovering of the pages, I'd say a sitemap would solve all problems

I tried a vite plugin to automatically generate it 

it looks like this 

![image](https://user-images.githubusercontent.com/59060246/225252387-b1c6dd28-d264-4292-9aab-44798378227b.png)

**Comment by shortcuts** [comment] 2023-03-15 08:36
I guess the plugin is not able to discover your urls too then :/ You should have a `url` block for each URL of your website: https://www.algolia.com/sitemap.xml

**Comment by siduck** [comment] 2023-03-15 09:18
> I guess the plugin is not able to discover your urls too then :/ You should have a `url` block for each URL of your website, see https://www.algolia.com/sitemap.xml for example

ok i'll manually try first, do I include the hashes? 

![image](https://user-images.githubusercontent.com/59060246/225263468-62682b9a-dead-462f-8c4f-4222f6805852.png)

**Comment by shortcuts** [comment] 2023-03-15 10:11
> do I include the hashes? Wouldnt that redirect to homepage too :(

Yes, the sitemap should represent the final URL that you can access from a browser.

Note that this will only help the Crawler to properly discover URLs, but won't fix the render issue. Hash routing have a huge impact on SEO and discovery in general, I'd recommend to switch to an other history mode if that's possible for you

**Comment by siduck** [comment] 2023-03-15 10:21
> > do I include the hashes? Wouldnt that redirect to homepage too :(
> 
> Yes, the sitemap should represent the final URL that you can access from a browser.
> 
> Note that this will only help the Crawler to properly discover URLs, but won't fix the render issue. Hash routing have a huge impact on SEO and discovery in general, I'd recommend to switch to an other history mode if that's possible for you

I wasnt using hash routing before, but i got those 404 errors whenever reloading a non home route. I didnt know other methods than hashrouting to fix it :( https://github.com/solidjs/solid-router

**Comment by siduck** [comment] 2023-03-15 14:11
@shortcuts ok i stopped using hashrouter, now im using https://github.com/rafgraph/spa-github-pages , will it work?

**Comment by siduck** [comment] 2023-03-15 15:23
![image](https://user-images.githubusercontent.com/59060246/225357426-0c49dbc9-5418-4ea7-99f2-1a50bb167c5d.png)

https://nvchad.com/sitemap.xml

**Comment by shortcuts** [comment] 2023-03-16 12:51
Trying from the URL tester in the editor, it returns 404 on those new URLs 🤔 Is it client-side redirects? See https://crawler.algolia.com/admin/crawlers/e120626d-7695-43f1-b9bf-b19726525e9b/monitoring/list?reason=http_not_found for more details

**Comment by siduck** [comment] 2023-03-16 14:02
> Trying from the URL tester in the editor, it returns 404 on those new URLs thinking Is it client-side redirects? See https://crawler.algolia.com/admin/crawlers/e120626d-7695-43f1-b9bf-b19726525e9b/monitoring/list?reason=http_not_found for more details

i was using the trick provided by the github-spa-pages repo, they use a 404.html and whenever a non home route loads, it probably loads the 404.html first and then redirects to the preferred route

**Comment by siduck** [comment] 2023-03-16 14:04
@shortcuts so the crawler wont work with this method too? :disappointed:

**Comment by siduck** [comment] 2023-03-16 14:43
Just confiming, if thats the case then I cant use algolia and have to look for an alternative or write my own thing

**Comment by shortcuts** [comment] 2023-03-21 11:27
Hey, sorry for the delay. I'll investigate internally if we can do something about the hash router problem

**Comment by siduck** [comment] 2023-03-21 11:35
hi, you sure about this? crawling Non home routes redirects to the home page, idk how you'd work this out! Just tell me if supporting hashrouter isnt possible, Im on the way to write my own search functionality cuz of this but kept it on halt cuz your message, if algolia works then it'll save me lots of time!

**Closed** 2023-03-25 03:05 UTC

**Comment by siduck** [comment] 2023-03-25 03:34
ok now the search function works! cuz my site is generated by solid-ssg! :D

**Comment by shortcuts** [comment] 2023-03-25 08:59
sick!! Congrats
