### ISSUE TITLE
 Extractors returned 757 records, the maximum is 750

### ISSUE THREAD

**Issue by Zamiell** [algolia/docsearch#1658] opened 2022-11-08 17:03 UTC
Michael King told me to submit a bug report on GitHub.
You can reference our conversation here: https://discourse.algolia.com/t/extractors-returned-757-records-the-maximum-is-750/16493

**Comment by shortcuts** [comment] 2022-11-08 17:13
> Michael King told me to submit a bug report on GitHub.
> 
> You can reference our conversation here: https://discourse.algolia.com/t/extractors-returned-757-records-the-maximum-is-750/16493

Hey, yeah this is expected, not a bug. We set this hard limit to prevent crawling/indexing inconsistencies when fetching large pages.

Do you have the [aggregateContent](https://docsearch.algolia.com/docs/record-extractor/#aggregatecontent) option enabled? An other way to reduce the number of records is to ensure you have precise enough selectors

**Comment by Zamiell** [comment] 2022-11-08 19:44
Yes, as I explained in the linked thread, my Algolia config looks like this, which does include the `aggregateContent` option:

```ts
    algolia: {
      appId: "ZCC397CSMF", // cspell:disable-line
      apiKey: "212a5e2442aa0e579f2f7bba22ee529a",
      indexName: "isaacscript",
      contextualSearch: false, // Enabled by default; only useful for versioned sites.
      recordExtractor: ({ _, helpers }) =>
        helpers.docsearch({
          recordProps: {
            lvl0: "header h1",
            lvl1: "article h2",
            lvl2: "article h3",
            lvl3: "article h4",
            lvl4: "article h5",
            lvl5: "article h6",
            content: "article p, article li",
          },
          aggregateContent: true,
        }),
    },
 ```

However, this seems to have no effect.

> An other way to reduce the number of records is to ensure you have precise enough selectors

I'm not sure I understand. Are the selectors that you are referring to correspond to the "recordProps" values in the config? I am just using what is recommended by your support article, and they don't seem to be doing anything.

**Comment by shortcuts** [comment] 2022-11-08 21:05
> as I explained in the linked thread, my Algolia config looks like this,

sorry, was on the phone, I missed the link

> However, this seems to have no effect.

setting it to `true` is correct, disabling it creates a record for each `content` occurence in the DOM, so not what you are looking for here.

> Are the selectors that you are referring to correspond to the "recordProps" values in the config?

Yup indeed, but they seem correct. Looking at the page that trigger errors, it seems to index the `h4`s, which are all equal to `defined in` (e.g. https://isaacscript.github.io/isaac-typescript-definitions/enums/TrinketType/).

I'd personally remove the `lvl3` and higher selectors for those pages, as it does not bring value to the search. It will significantly reduce the number of records.

**Comment by Zamiell** [comment] 2022-11-08 21:21
Thank you shortcuts,

From what I understand of your reply, you want me to set the config to the following:

```ts
    algolia: {
      appId: "ZCC397CSMF", // cspell:disable-line
      apiKey: "212a5e2442aa0e579f2f7bba22ee529a",
      indexName: "isaacscript",
      contextualSearch: false, // Enabled by default; only useful for versioned sites.
      recordExtractor: ({ _, helpers }) =>
        helpers.docsearch({
          recordProps: {
            lvl0: "header h1",
            lvl1: "article h2",
            lvl2: "article h3",
          },
          aggregateContent: true,
        }),
    },
```

However, my worry is that this would somehow reduce the quality of the search results for other pages than `TrinketType` (and the other 2-3 "overflow" pages).

Subsequently, is there a way to make the `recordExtractor` section only apply to the "overflow" pages? Or would this not be relevant for my use case?

**Comment by shortcuts** [comment] 2022-11-08 21:30
> Subsequently, is there a way to make the `recordExtractor` section only apply to the "overflow" pages? Or would this not be relevant for my use case?

actions can be scoped to a specific path, see https://www.algolia.com/doc/tools/crawler/apis/configuration/actions/. You can use the snippet you shared for only those pages, and keep the other pages unchanged

**Comment by shortcuts** [comment] 2022-11-16 10:42
closing until you answer if there's any other issue :D

**Closed by shortcuts** 2022-11-16 10:42 UTC

**Comment by Zamiell** [comment] 2023-01-14 18:22
> actions can be scoped to a specific path, see https://www.algolia.com/doc/tools/crawler/apis/configuration/actions/. You can use the snippet you shared for only those pages, and keep the other pages unchanged

Thanks, I'll try that out.

> closing until you answer if there's any other issue :D

@shortcuts Even with the config that is specified in my previous post in this thread, I still get Algolia crawler errors:

![image](https://user-images.githubusercontent.com/5511220/212489547-66296dfa-1a3c-4151-a2e7-f113ec480de3.png)

So it looks like the `aggregateContent` tag isn't working properly. Can you confirm?

**Comment by shortcuts** [comment] 2023-02-06 10:56
Hey @Zamiell, looking at your Crawler configuration, I don't see the changes above being applied. Do you need help applying the changes?

**Comment by Zamiell** [comment] 2023-02-06 17:11
@shortcuts What do you mean by "the changes above"? Do you mean making the configuration scoped to a more specific path? I don't want to do that right now because I just want to have the simplest possible configuration, to eliminate any possible bugs. Yet even though the `aggregateContent` is applying to **the entire repository**, it still doesn't work at all!

For reference, here is my configuration: https://github.com/IsaacScript/isaacscript/blob/main/packages/docs/docusaurus.config.js#L91-L105

**Comment by shortcuts** [comment] 2023-02-06 20:59
Docusaurus does not control the indexing, only the search, so [those lines](https://github.com/IsaacScript/isaacscript/blob/main/packages/docs/docusaurus.config.js#L96-L104) should be updated in the Crawler config directly

**Comment by Zamiell** [comment] 2023-02-06 21:03
@shortcuts Can you explain how to update the crawler configuration directly?

I assume that you are directing me to this page:

![image](https://user-images.githubusercontent.com/5511220/217085562-c181a4af-7987-4c5c-9d69-efc008bf718d.png)

But I don't see any boxes to paste in a `recordExtractor` or a `recordProps` or anything like that.

**Comment by shortcuts** [comment] 2023-02-06 21:14
The editor button on the left of your screenshot, it will show a JSON config that you can edit.

From my past comment, https://github.com/algolia/docsearch/issues/1658#issuecomment-1307852535, you can find links to the API reference, guides and stuff:
- https://www.algolia.com/doc/tools/crawler/getting-started/crawler-configuration/
- https://www.algolia.com/doc/tools/crawler/apis/configuration/

let me know if you need further helping with this!

**Comment by Zamiell** [comment] 2023-02-06 23:15
Great, thank you, that got me on to the right track.

I'll write up a guide on how to solve this problem for others that encounter it.

**Comment by Zamiell** [comment] 2023-02-06 23:58
# HI

Sometimes, when Algolia goes to index a very large page, it will give an error:

```text
Extractors returned too many records
```

To fix this, you have to change the `recordExtractor` configuration for the Algolia crawler.

- First, go to the Crawler homepage: https://crawler.algolia.com/admin/crawlers/
- Click on the index that is triggering the error in question, which will take you to the "Overview" page.
- Click on "Editor" from the left menu, which will open up a VSCode-like interface.
- Scroll down to the `actions` array that is part of the object passed to the `Crawler` constructor.

Personally, I'm using Algolia to crawl my Docusaurus website. For reference, the default `actions` array for a Docusaurus website (as of February 2023) looks something like this:

```js
  actions: [
    {
      indexName: "foo",
      pathsToMatch: ["https://foo.github.io/**"],
      recordExtractor: ({ $, helpers }) => {
        // priority order: deepest active sub list header -> navbar active item -> 'Documentation'
        const lvl0 =
          $(
            ".menu__link.menu__link--sublist.menu__link--active, .navbar__item.navbar__link--active"
          )
            .last()
            .text() || "Documentation";

        return helpers.docsearch({
          recordProps: {
            content: "article p, article li, article td:last-child",
            lvl0: {
              selectors: "",
              defaultValue: lvl0,
            },
            lvl1: "header h1",
            lvl2: "article h2",
            lvl3: "article h3",
            lvl4: "article h4",
            lvl5: "article h5, article td:first-child",
          },
          indexHeadings: true,
        });
      },
    },
  ],
```

- The first thing you should try is to add `aggregateContent: true` to the bottom of the object (below the `indexHeadings` line).
- Then, trigger a re-index of the site to see if the error still happens. (You can force a re-index by clicking on the "Restart crawling" button on the "Overview" page.)

You can learn more about the `aggregateContent` option on [the `recordExtractor` documentation page](https://docsearch.algolia.com/docs/record-extractor/#aggregatecontent). In short, it reduces the total amount of records that are generated for any particular page, while leaving the resulting quality of the index the same as it was before.

If that made the error go away, then great! You're done. If it didn't, then we can try customizing the indexing selectors that are used for the problematic pages.

In order to do that, we have to add another action by copy-pasting our existing config. For example, let's imagine that we have 3 specific pages that cause the "too many records" error: Foo, Bar, and Baz. First, we need to copy paste the config into another action, and then modify the `pathsToMatch` entry for each of the two actions:

```js
  actions: [
    {
      indexName: "foo",
      pathsToMatch: [
        "https://foo.github.io/**",
        "!https://foo.github.io/docs/Foo/",
        "!https://foo.github.io/docs/Bar/",
        "!https://foo.github.io/docs/Baz/",
      ],
      recordExtractor: ({ $, helpers }) => {
        // priority order: deepest active sub list header -> navbar active item -> 'Documentation'
        const lvl0 =
          $(
            ".menu__link.menu__link--sublist.menu__link--active, .navbar__item.navbar__link--active"
          )
            .last()
            .text() || "Documentation";

        return helpers.docsearch({
          recordProps: {
            content: "article p, article li, article td:last-child",
            lvl0: {
              selectors: "",
              defaultValue: lvl0,
            },
            lvl1: "header h1",
            lvl2: "article h2",
            lvl3: "article h3",
            lvl4: "article h4",
            lvl5: "article h5, article td:first-child",
          },
          indexHeadings: true,
          aggregateContent: true,
        });
      },
    },
    {
      indexName: "foo",
      pathsToMatch: [
        "https://foo.github.io/docs/Foo/",
        "https://foo.github.io/docs/Bar/",
        "https://foo.github.io/docs/Baz/",
      ],
      recordExtractor: ({ $, helpers }) => {
        // priority order: deepest active sub list header -> navbar active item -> 'Documentation'
        const lvl0 =
          $(
            ".menu__link.menu__link--sublist.menu__link--active, .navbar__item.navbar__link--active"
          )
            .last()
            .text() || "Documentation";

        return helpers.docsearch({
          recordProps: {
            content: "article p, article li, article td:last-child",
            lvl0: {
              selectors: "",
              defaultValue: lvl0,
            },
            lvl1: "header h1",
            lvl2: "article h2",
            lvl3: "article h3",
            lvl4: "article h4",
            lvl5: "article h5, article td:first-child",
          },
          indexHeadings: true,
          aggregateContent: true,
        });
      },
    },
  ],
```

First, note that we are generating a second action because we don't want to influence or somehow harm the search results of the normal non-problematic pages on our website. We want to only tinker with the problematic pages specifically.

Second, note that we have to negate the problematic URLs in the first action because the crawler will [create a record for each matched action](https://www.algolia.com/doc/tools/crawler/apis/configuration/actions/#how-to-use). In other words, there is no ordering of actions - all URLs get processed through all actions.

Now, we have a action that will only apply to problematic pages, but right now it is just the exact same config (since it was copy-pasted). So, the next step is to modify the selector on the second action by removing the `lvl5` line. Save the config and trigger a re-index to see if the problem still happens.

If the problem persists, we can remove the `lvl4` line. And then, if that doesn't work, we can remove the `lvl3` line. And then the `lvl2` line. (The idea here is that we are removing more and more content until we get the remaining stuff to get swallowed by the crawler.)

If you you only have `lvl0` and `lvl1` and you _still_ get the error, then you are probably screwed, because `lvl1` appears to be a mandatory field in the config.

**Comment by shortcuts** [comment] 2023-02-07 11:37
Lovely!! would you mind updating [the doc](https://docsearch.algolia.com/docs/record-extractor/#reduce-the-number-of-records) to add a link to your comment?

**Comment by Zamiell** [comment] 2023-02-07 16:45
no, but feel free to copy paste the relevant parts
